/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.component;

import enumvalue.RoleEnum;

/**
 *
 * @author limingxia
 */
public class AvatarPanel extends javax.swing.JPanel {

    // because of cai, give default value
    private String email = "test@gmail.com";
    private String roleType = RoleEnum.SYSTEM_ADMIN.getRole();
    private String avatar = "icon";

    /**
     * Creates new form AvatarPanel
     */
    public AvatarPanel() {
        initComponents();
    }

    public AvatarPanel(String email, String roleType) {
        this.email = email;
        this.roleType = roleType;
        this.avatar = roleType; // avatar name is same as roleType
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        avatarPanel = new ui.component.ImageAvatar();
        userNameLbl = new javax.swing.JLabel();
        roleTypeLbl = new javax.swing.JLabel();

        setOpaque(false);

        avatarPanel.setBorderSize(4);
        avatarPanel.setBorderSpace(0);
        avatarPanel.setImage(new javax.swing.ImageIcon(getClass().getResource("/assets/default/" + avatar + ".png")));

        userNameLbl.setBackground(new java.awt.Color(255, 255, 255));
        userNameLbl.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        userNameLbl.setForeground(new java.awt.Color(255, 255, 255));
        userNameLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userNameLbl.setText(email);

        roleTypeLbl.setBackground(new java.awt.Color(255, 255, 255));
        roleTypeLbl.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        roleTypeLbl.setForeground(new java.awt.Color(255, 255, 255));
        roleTypeLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roleTypeLbl.setText(roleType+"");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(avatarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(userNameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(roleTypeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(avatarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userNameLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roleTypeLbl))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ui.component.ImageAvatar avatarPanel;
    private javax.swing.JLabel roleTypeLbl;
    private javax.swing.JLabel userNameLbl;
    // End of variables declaration//GEN-END:variables

}
