/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Pilot;

import dao.FlightDao;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Flight;
import org.apache.commons.lang3.ObjectUtils;

/**
 *
 * @author miaoc
 */
public class PilotATCcommandPanel extends javax.swing.JPanel {
    private List<Flight> flights = new ArrayList<>();
    /**
     * Creates new form PilotATCcommandPanel
     */
    public PilotATCcommandPanel() {
        initComponents();
        initFlights();
        populateFlight(flights);
    }
    private void initFlights() {
        flights = FlightDao.queryFlightList();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundPanel1 = new ui.component.RoundPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblFlight = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        btnView = new javax.swing.JButton();
        lblTerminal = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblRunway = new javax.swing.JLabel();
        txtFlight = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtRwy = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTerminal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnNewOrder = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtGate = new javax.swing.JTextField();

        roundPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblFlight.setBackground(new java.awt.Color(204, 204, 204));
        tblFlight.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Flight No."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblFlight);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(106, 133, 182));
        jLabel4.setText("Flight List");

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        lblTerminal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/AirportMap_TERM_B.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(106, 133, 182));
        jLabel5.setText("Runway Assigned");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(106, 133, 182));
        jLabel6.setText("Terminal Assigned");

        lblRunway.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/AirportMap_RWY14.png"))); // NOI18N

        txtFlight.setEditable(false);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(106, 133, 182));
        jLabel7.setText("Flight No.");

        txtRwy.setEditable(false);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(106, 133, 182));
        jLabel8.setText("RWY");

        txtTerminal.setEditable(false);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(106, 133, 182));
        jLabel9.setText("Terminal");

        btnNewOrder.setText("Update Status");
        btnNewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewOrderActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(106, 133, 182));
        jLabel10.setText("Gate");

        txtGate.setEditable(false);

        javax.swing.GroupLayout roundPanel1Layout = new javax.swing.GroupLayout(roundPanel1);
        roundPanel1.setLayout(roundPanel1Layout);
        roundPanel1Layout.setHorizontalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblRunway)
                                .addComponent(jLabel5))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, roundPanel1Layout.createSequentialGroup()
                                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(roundPanel1Layout.createSequentialGroup()
                                        .addComponent(txtFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(63, 63, 63)))
                                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(txtRwy))))
                        .addGap(53, 53, 53)
                        .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(lblTerminal)
                            .addGroup(roundPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTerminal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtGate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNewOrder)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        roundPanel1Layout.setVerticalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel1Layout.createSequentialGroup()
                        .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFlight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRwy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(txtTerminal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(txtGate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRunway))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTerminal)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnView)
                    .addComponent(btnNewOrder))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addComponent(roundPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(roundPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblFlight.getSelectedRow();
        if (selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Select a airline to view command");
            return;
        }
        if (ObjectUtils.isEmpty(flights)) {
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblFlight.getModel();
        String flight_number = model.getValueAt(selectedRowIndex, 0).toString();
        txtFlight.setText(flight_number);
        
        //Get necessary info
        int ParkingLotAndTerminal = 0;
        String info = "";
        for (Flight f : flights) {
            if (f.getFlightNo().equals(flight_number)){
                if (f.getParkingLot() == null){
                    ParkingLotAndTerminal = 0;
                }else{
                    ParkingLotAndTerminal = f.getParkingLot();
                }
                
            }
        }
        info = Integer.toString(ParkingLotAndTerminal);
        if(ParkingLotAndTerminal<10){
            info = "0"+info;
        }
        
        txtGate.setText(Integer.toString(ParkingLotAndTerminal));
        
        String[] arrOfStr = info.split("", 2);
        
        
        //Set Runway and Terminal
        String rwy = "RWY27";
        String terminal = "B";
        
        if (Integer.parseInt(arrOfStr[0]) == 0){
            terminal = "HOLDING";
        }
        if (Integer.parseInt(arrOfStr[0]) == 1){
            terminal = "A";
        }
        if (Integer.parseInt(arrOfStr[0]) == 2){
            terminal = "B";
        }
        if (Integer.parseInt(arrOfStr[0]) == 3){
            terminal = "C";
        }
        
        if (Integer.parseInt(arrOfStr[1]) == 0){
            terminal = "HOLDING";
        }
        if (Integer.parseInt(arrOfStr[1]) == 1){
            rwy = "RWY14";
        }
        if (Integer.parseInt(arrOfStr[1]) == 2){
            rwy = "RWY16";
        }
        if (Integer.parseInt(arrOfStr[1]) == 3){
            rwy = "RWY22";
        }
        if (Integer.parseInt(arrOfStr[1]) == 4){
            rwy = "RWY27";
        }
        
        if(rwy.equals("HOLDING") || terminal.equals("HOLDING")){
            txtRwy.setText(rwy);
            txtTerminal.setText(terminal);
            
            if(rwy.equals("HOLDING") && terminal.equals("HOLDING")){
                return;
            }
            if(rwy.equals("HOLDING")){
                rwy = "RWY14";
            }
            if(terminal.equals("HOLDING")){
                terminal = "A";
            }
            
        }
        
        txtRwy.setText(rwy);
        txtTerminal.setText(terminal);
        
        String root = System.getProperty("user.dir");
        String FileName="AirportMap_"+rwy+".png"; //change the file name here
        String FileName2 = "AirportMap_TERM_" + terminal + ".png";
        String filePathRunway = root+File.separator+"src"+File.separator+"assets"+File.separator+FileName;
        String filePathTerminal = root+File.separator+"src"+File.separator+"assets"+File.separator+FileName2;
        ImageIcon runway = new ImageIcon(filePathRunway);
        ImageIcon ter = new ImageIcon(filePathTerminal);
        
        lblRunway.setIcon(runway);
        lblTerminal.setIcon(ter);
    }//GEN-LAST:event_btnViewActionPerformed


    private void btnNewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewOrderActionPerformed
        // TODO add your handling code here:
        initFlights(); 
        JOptionPane.showMessageDialog(this, "Status Updated");
    }//GEN-LAST:event_btnNewOrderActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNewOrder;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblRunway;
    private javax.swing.JLabel lblTerminal;
    private ui.component.RoundPanel roundPanel1;
    private javax.swing.JTable tblFlight;
    private javax.swing.JTextField txtFlight;
    private javax.swing.JTextField txtGate;
    private javax.swing.JTextField txtRwy;
    private javax.swing.JTextField txtTerminal;
    // End of variables declaration//GEN-END:variables
    private void populateFlight(List<Flight> flights) {
        DefaultTableModel model = (DefaultTableModel) tblFlight.getModel();
        model.setRowCount(0);

        if (ObjectUtils.isEmpty(flights)) {
            return;
        }

        for (Flight f : flights) {

            Object[] row = new Object[1];
            row[0] = f;
            //row[1] = f.getFlightCompany().getFcName();
            //row[2] = DateUtils.dateToString(f.getDepartureTime());
            //row[3] = DateUtils.dateToString(f.getArrivalTime());
            //row[4] = f.getDuration();
            //row[1] = f.getStatus();

            model.addRow(row);
        }
    }
}
