/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.AirTraficController;

import dao.FlightDao;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Flight;
import org.apache.commons.lang3.ObjectUtils;
import utils.emailNotification;
import static utils.Constant.DATABASE_ERROR;
/**
 *
 * @author limingxia
 */
public class AirTrafficControllerCommandPanel extends javax.swing.JPanel {
    private List<Flight> flights = new ArrayList<>();
    /**
     * Creates new form contentTablePanel
     */
    public AirTrafficControllerCommandPanel() {
        initComponents();
        initFlights();
        populateMonitor(flights);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        roundPanel1 = new ui.component.RoundPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMonitor = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        roundPanel2 = new ui.component.RoundPanel();
        btnRWY14 = new javax.swing.JButton();
        btnRWY22 = new javax.swing.JButton();
        btnRWY27 = new javax.swing.JButton();
        btnRWY16 = new javax.swing.JButton();
        btnRunwayHolding = new javax.swing.JButton();
        btnTemA = new javax.swing.JButton();
        tbnTemB = new javax.swing.JButton();
        btnTemC = new javax.swing.JButton();
        btnTemWaiting = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        roundPanel3 = new ui.component.RoundPanel();
        txtRWY = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnSendCommand = new javax.swing.JButton();
        txtTER = new javax.swing.JTextField();
        roundPanel4 = new ui.component.RoundPanel();
        jLabel12 = new javax.swing.JLabel();
        txtGate = new javax.swing.JTextField();
        btnGate = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 204, 204));
        setOpaque(false);

        roundPanel1.setBackground(new java.awt.Color(204, 204, 204));

        tblMonitor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Flight No.", "Status", "Runway", "Terminal"
            }
        ));
        jScrollPane2.setViewportView(tblMonitor);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(106, 133, 182));
        jLabel6.setText("Monitor");

        javax.swing.GroupLayout roundPanel1Layout = new javax.swing.GroupLayout(roundPanel1);
        roundPanel1.setLayout(roundPanel1Layout);
        roundPanel1Layout.setHorizontalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(206, 206, 206)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        roundPanel1Layout.setVerticalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                .addContainerGap())
        );

        roundPanel2.setBackground(new java.awt.Color(204, 204, 204));

        btnRWY14.setBackground(new java.awt.Color(204, 255, 255));
        btnRWY14.setText("RWY 14");
        btnRWY14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRWY14ActionPerformed(evt);
            }
        });

        btnRWY22.setBackground(new java.awt.Color(204, 255, 255));
        btnRWY22.setText("RWY 22");
        btnRWY22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRWY22ActionPerformed(evt);
            }
        });

        btnRWY27.setBackground(new java.awt.Color(204, 255, 255));
        btnRWY27.setText("RWY 27");
        btnRWY27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRWY27ActionPerformed(evt);
            }
        });

        btnRWY16.setBackground(new java.awt.Color(204, 255, 255));
        btnRWY16.setText("RWY 16");
        btnRWY16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRWY16ActionPerformed(evt);
            }
        });

        btnRunwayHolding.setBackground(new java.awt.Color(255, 153, 0));
        btnRunwayHolding.setForeground(new java.awt.Color(0, 0, 0));
        btnRunwayHolding.setText("Holding");
        btnRunwayHolding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRunwayHoldingActionPerformed(evt);
            }
        });

        btnTemA.setBackground(new java.awt.Color(204, 255, 255));
        btnTemA.setText("Terminal A");
        btnTemA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTemAActionPerformed(evt);
            }
        });

        tbnTemB.setBackground(new java.awt.Color(204, 255, 255));
        tbnTemB.setText("Terminal B");
        tbnTemB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnTemBActionPerformed(evt);
            }
        });

        btnTemC.setBackground(new java.awt.Color(204, 255, 255));
        btnTemC.setText("Terminal C");
        btnTemC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTemCActionPerformed(evt);
            }
        });

        btnTemWaiting.setBackground(new java.awt.Color(255, 153, 0));
        btnTemWaiting.setForeground(new java.awt.Color(0, 0, 0));
        btnTemWaiting.setText("Holding");
        btnTemWaiting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTemWaitingActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(106, 133, 182));
        jLabel7.setText("Assign Runway");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(106, 133, 182));
        jLabel9.setText("Assign Terminal");

        javax.swing.GroupLayout roundPanel2Layout = new javax.swing.GroupLayout(roundPanel2);
        roundPanel2.setLayout(roundPanel2Layout);
        roundPanel2Layout.setHorizontalGroup(
            roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTemWaiting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(roundPanel2Layout.createSequentialGroup()
                        .addGroup(roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(roundPanel2Layout.createSequentialGroup()
                                .addComponent(btnRWY14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRWY16))
                            .addGroup(roundPanel2Layout.createSequentialGroup()
                                .addComponent(btnRWY22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRWY27))
                            .addComponent(btnRunwayHolding, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(tbnTemB)
                            .addComponent(btnTemA)
                            .addComponent(btnTemC))
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addContainerGap())
        );
        roundPanel2Layout.setVerticalGroup(
            roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRWY14)
                    .addComponent(btnRWY16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRWY22)
                    .addComponent(btnRWY27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRunwayHolding)
                .addGap(3, 3, 3)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTemA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbnTemB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTemC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTemWaiting)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        roundPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(106, 133, 182));
        jLabel8.setText("Runway");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(106, 133, 182));
        jLabel10.setText("Terminal");

        btnSendCommand.setBackground(new java.awt.Color(255, 0, 0));
        btnSendCommand.setForeground(new java.awt.Color(255, 255, 102));
        btnSendCommand.setText("SEND COMMAND");
        btnSendCommand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendCommandActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roundPanel3Layout = new javax.swing.GroupLayout(roundPanel3);
        roundPanel3.setLayout(roundPanel3Layout);
        roundPanel3Layout.setHorizontalGroup(
            roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTER, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSendCommand)
                    .addGroup(roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10)
                        .addGroup(roundPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(18, 18, 18)
                            .addComponent(txtRWY, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        roundPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtRWY, txtTER});

        roundPanel3Layout.setVerticalGroup(
            roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRWY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSendCommand)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        roundPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtRWY, txtTER});

        roundPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(106, 133, 182));
        jLabel12.setText("Gate Generater ");

        txtGate.setEditable(false);

        btnGate.setText("Generate Best Gate");
        btnGate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roundPanel4Layout = new javax.swing.GroupLayout(roundPanel4);
        roundPanel4.setLayout(roundPanel4Layout);
        roundPanel4Layout.setHorizontalGroup(
            roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundPanel4Layout.createSequentialGroup()
                        .addGroup(roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtGate))
                        .addGap(48, 48, 48))
                    .addGroup(roundPanel4Layout.createSequentialGroup()
                        .addComponent(btnGate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        roundPanel4Layout.setVerticalGroup(
            roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGate)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(roundPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roundPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(roundPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(roundPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roundPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(roundPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(roundPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(roundPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void initFlights() {
        flights = FlightDao.queryFlightList();
    }
    
    private void btnTemAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTemAActionPerformed
        // TODO add your handling code here:
        txtTER.setText("A");
    }//GEN-LAST:event_btnTemAActionPerformed

    private void btnSendCommandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendCommandActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblMonitor.getSelectedRow();
        if (selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Select a airline to view command");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblMonitor.getModel();
        String flight_number = model.getValueAt(selectedRowIndex, 0).toString();
        
        int command = 0;
        String temp = "";
        
        if (txtTER.getText().equals("") || txtRWY.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Empty Command Not Allowed");
            return;
        }
        
        if (txtTER.getText().equals("HOLDING")){
            temp += "0";
        }else if (txtTER.getText().equals("A")){
            temp += "1";
        }else if (txtTER.getText().equals("B")){
            temp += "2";
        }else {
            temp += "3";
        }
        
        if (txtRWY.getText().equals("HOLDING")){
            temp += "0";
        }else if (txtRWY.getText().equals("14")){
            temp += "1";
        }else if (txtRWY.getText().equals("16")){
            temp += "2";
        }else if (txtRWY.getText().equals("22")){
            temp += "3";
        }else {
            temp += "4";
        }
        
        command = Integer.parseInt(temp);
        
        if (!FlightDao.updateFlightTerminalAndRWY(command, flight_number)) {
            JOptionPane.showMessageDialog(this, DATABASE_ERROR);
            return;
        }else{
            JOptionPane.showMessageDialog(this, "Command send");
            initFlights();
            populateMonitor(flights);
            return;
        }
    }//GEN-LAST:event_btnSendCommandActionPerformed

    private void tbnTemBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnTemBActionPerformed
        // TODO add your handling code here:
        txtTER.setText("B");
    }//GEN-LAST:event_tbnTemBActionPerformed

    private void btnTemCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTemCActionPerformed
        // TODO add your handling code here:
        txtTER.setText("C");
    }//GEN-LAST:event_btnTemCActionPerformed

    private void btnRWY14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRWY14ActionPerformed
        // TODO add your handling code here:
        txtRWY.setText("14");
    }//GEN-LAST:event_btnRWY14ActionPerformed

    private void btnRWY16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRWY16ActionPerformed
        // TODO add your handling code here:
        txtRWY.setText("16");
    }//GEN-LAST:event_btnRWY16ActionPerformed

    private void btnRWY22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRWY22ActionPerformed
        // TODO add your handling code here:
        txtRWY.setText("22");
    }//GEN-LAST:event_btnRWY22ActionPerformed

    private void btnRWY27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRWY27ActionPerformed
        // TODO add your handling code here:
        txtRWY.setText("27");
    }//GEN-LAST:event_btnRWY27ActionPerformed

    private void btnTemWaitingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTemWaitingActionPerformed
        // TODO add your handling code here:
        txtTER.setText("HOLDING");
    }//GEN-LAST:event_btnTemWaitingActionPerformed

    private void btnRunwayHoldingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRunwayHoldingActionPerformed
        // TODO add your handling code here:
        txtRWY.setText("HOLDING");
    }//GEN-LAST:event_btnRunwayHoldingActionPerformed

    private void btnGateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGateActionPerformed
        // TODO add your handling code here:
        String temp = "";
        
        if (txtTER.getText().equals("") || txtRWY.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Choose Runway and Terminal to Generate gate");
            return;
        }
        
        if (txtTER.getText().equals("HOLDING")){
            temp += "0";
        }else if (txtTER.getText().equals("A")){
            temp += "1";
        }else if (txtTER.getText().equals("B")){
            temp += "2";
        }else {
            temp += "3";
        }
        
        if (txtRWY.getText().equals("HOLDING")){
            temp += "0";
        }else if (txtRWY.getText().equals("14")){
            temp += "1";
        }else if (txtRWY.getText().equals("16")){
            temp += "2";
        }else if (txtRWY.getText().equals("22")){
            temp += "3";
        }else {
            temp += "4";
        }
        txtGate.setText(temp);
    }//GEN-LAST:event_btnGateActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGate;
    private javax.swing.JButton btnRWY14;
    private javax.swing.JButton btnRWY16;
    private javax.swing.JButton btnRWY22;
    private javax.swing.JButton btnRWY27;
    private javax.swing.JButton btnRunwayHolding;
    private javax.swing.JButton btnSendCommand;
    private javax.swing.JButton btnTemA;
    private javax.swing.JButton btnTemC;
    private javax.swing.JButton btnTemWaiting;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private ui.component.RoundPanel roundPanel1;
    private ui.component.RoundPanel roundPanel2;
    private ui.component.RoundPanel roundPanel3;
    private ui.component.RoundPanel roundPanel4;
    private javax.swing.JTable tblMonitor;
    private javax.swing.JButton tbnTemB;
    private javax.swing.JTextField txtGate;
    private javax.swing.JTextField txtRWY;
    private javax.swing.JTextField txtTER;
    // End of variables declaration//GEN-END:variables
    
    private void populateMonitor(List<Flight> flights) {
        DefaultTableModel model = (DefaultTableModel) tblMonitor.getModel();
        model.setRowCount(0);
        int ParkingLotAndTerminal = 0;
        String info = "";
        String rwy = "";
        String terminal = "";
        
        if (ObjectUtils.isEmpty(flights)) {
            return;
        }

        for (Flight f : flights) {

            Object[] row = new Object[4];
            row[0] = f;
            //row[1] = f.getFlightCompany().getFcName();
            //row[2] = DateUtils.dateToString(f.getDepartureTime());
            //row[3] = DateUtils.dateToString(f.getArrivalTime());
            //row[4] = f.getDuration();
            if (f.getParkingLot() == null){
                ParkingLotAndTerminal = 0;
            } else{
                ParkingLotAndTerminal = f.getParkingLot();
                
            }
            if (f.getStatus() == 0){
                    row[1] = "NORMAL";
                }else if (f.getStatus() == 1){
                    row[1] = "DELAY";
                }else if (f.getStatus() == 2){
                    row[1] = "CANCEL";
                }
            
            info = Integer.toString(ParkingLotAndTerminal);
            if(ParkingLotAndTerminal<10){
                info = "0"+info;
            }
            String[] arrOfStr = info.split("", 2);
            if (Integer.parseInt(arrOfStr[0]) == 0){
                terminal = "HOLDING";
            }
            if (Integer.parseInt(arrOfStr[0]) == 1){
                terminal = "Terminal A";
            }
            if (Integer.parseInt(arrOfStr[0]) == 2){
                terminal = "Terminal B";
            }
            if (Integer.parseInt(arrOfStr[0]) == 3){
               terminal = "Terminal C";
            }   
        
            if (Integer.parseInt(arrOfStr[1]) == 0){
                rwy = "HOLDING";
            }
            if (Integer.parseInt(arrOfStr[1]) == 1){
                rwy = "RWY14";
            }
            if (Integer.parseInt(arrOfStr[1]) == 2){
                rwy = "RWY16";
            }
            if (Integer.parseInt(arrOfStr[1]) == 3){
                rwy = "RWY22";
            }
            if (Integer.parseInt(arrOfStr[1]) == 4){
                rwy = "RWY27";
            }
            row[2] = rwy;
            row[3] = terminal;
            model.addRow(row);
        }
    }
}
