/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Passenger;

import dao.FlightDao;
import dao.PassportDao;
import dao.PersonDao;
import dao.TicketDao;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.Objects;
import javax.swing.JOptionPane;
import model.Flight;
import model.Person;
import model.Ticket;
import model.Passport;

/**
 *
 * @author Jiaf
 */
public class FlightInfoPanel extends javax.swing.JPanel {

    Person curPerson = new Person();

    /**
     * Creates new form FlightInfoPanel
     */
    public FlightInfoPanel(Person p) {
        curPerson = p;
        initComponents();
        initialData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundPanel1 = new ui.component.RoundPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtArvTime = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtArrivalAirport = new javax.swing.JTextField();
        txtDepaTime = new javax.swing.JTextField();
        txtDepatureAirport = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFlightNo = new javax.swing.JTextField();
        roundPanel2 = new ui.component.RoundPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtLaggage = new javax.swing.JTextField();
        txtSeat = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtGate = new javax.swing.JTextField();
        txtBording = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        illLbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        roundPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(106, 133, 182));
        jLabel6.setText("Arrival Time");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(106, 133, 182));
        jLabel2.setText("Depature Airport");

        txtArvTime.setEditable(false);
        txtArvTime.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtArvTime.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(106, 133, 182)));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(106, 133, 182));
        jLabel4.setText("Arrival Airport");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(106, 133, 182));
        jLabel1.setText("Depature Time");

        txtArrivalAirport.setEditable(false);
        txtArrivalAirport.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtArrivalAirport.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(106, 133, 182)));

        txtDepaTime.setEditable(false);
        txtDepaTime.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtDepaTime.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(106, 133, 182)));
        txtDepaTime.setDisabledTextColor(new java.awt.Color(255, 255, 255));

        txtDepatureAirport.setEditable(false);
        txtDepatureAirport.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtDepatureAirport.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(106, 133, 182)));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(106, 133, 182));
        jLabel3.setText("Flight Number");

        txtFlightNo.setEditable(false);
        txtFlightNo.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtFlightNo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(106, 133, 182)));

        roundPanel2.setBackground(new java.awt.Color(203, 238, 248));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(106, 133, 182));
        jLabel5.setText("BOARDING PASS");

        jLabel8.setText("NAME");

        jLabel11.setText("GATE");

        jLabel12.setText("BOARDING");

        jLabel13.setText("SEAT");

        txtLaggage.setEditable(false);
        txtLaggage.setBackground(new java.awt.Color(203, 238, 248));
        txtLaggage.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtLaggage.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(106, 133, 182)));

        txtSeat.setEditable(false);
        txtSeat.setBackground(new java.awt.Color(203, 238, 248));
        txtSeat.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtSeat.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(106, 133, 182)));

        txtName.setEditable(false);
        txtName.setBackground(new java.awt.Color(203, 238, 248));
        txtName.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(106, 133, 182)));

        txtGate.setEditable(false);
        txtGate.setBackground(new java.awt.Color(203, 238, 248));
        txtGate.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtGate.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(106, 133, 182)));

        txtBording.setEditable(false);
        txtBording.setBackground(new java.awt.Color(203, 238, 248));
        txtBording.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtBording.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(106, 133, 182)));

        jLabel14.setText("LAGGAGE");

        illLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bloom-woman-with-her-suitcase-sitting-near-airport-tablo-and-looking-at-her-watch.png"))); // NOI18N

        javax.swing.GroupLayout roundPanel2Layout = new javax.swing.GroupLayout(roundPanel2);
        roundPanel2.setLayout(roundPanel2Layout);
        roundPanel2Layout.setHorizontalGroup(
            roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLaggage)
                    .addGroup(roundPanel2Layout.createSequentialGroup()
                        .addGroup(roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(roundPanel2Layout.createSequentialGroup()
                                .addComponent(txtGate, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(txtSeat, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addGroup(roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBording, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)))
                            .addComponent(jLabel14)
                            .addGroup(roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(roundPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addGap(97, 97, 97)
                                    .addComponent(jLabel13))
                                .addComponent(jLabel8)
                                .addComponent(txtName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(illLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(144, 144, 144))
        );
        roundPanel2Layout.setVerticalGroup(
            roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(illLbl)
                        .addGap(30, 30, 30))
                    .addGroup(roundPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLaggage, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGate, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSeat, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBording, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))))
        );

        javax.swing.GroupLayout roundPanel1Layout = new javax.swing.GroupLayout(roundPanel1);
        roundPanel1.setLayout(roundPanel1Layout);
        roundPanel1Layout.setHorizontalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtFlightNo, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(roundPanel1Layout.createSequentialGroup()
                                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(txtDepaTime, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDepatureAirport, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(51, 51, 51)
                                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtArvTime)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtArrivalAirport, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(roundPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        roundPanel1Layout.setVerticalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFlightNo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDepaTime, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtArvTime, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtArrivalAirport, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDepatureAirport, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(roundPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roundPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel illLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private ui.component.RoundPanel roundPanel1;
    private ui.component.RoundPanel roundPanel2;
    private javax.swing.JTextField txtArrivalAirport;
    private javax.swing.JTextField txtArvTime;
    private javax.swing.JTextField txtBording;
    private javax.swing.JTextField txtDepaTime;
    private javax.swing.JTextField txtDepatureAirport;
    private javax.swing.JTextField txtFlightNo;
    private javax.swing.JTextField txtGate;
    private javax.swing.JTextField txtLaggage;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSeat;
    // End of variables declaration//GEN-END:variables
    
    public void initialData() {

        String tickeId = PersonDao.getTicketByAccount(curPerson.getAccount());
        Ticket t = TicketDao.getTicketById(tickeId);

        String flightNo = t.getFlightNo();
        Flight f = FlightDao.queryFlightByID(flightNo);
        Passport p = PassportDao.queryPassportNoByPid(curPerson.getPersonID());
        if (Objects.isNull(p) || Objects.isNull(t) || Objects.isNull(f)) {
            setBlank();
            JOptionPane.showMessageDialog(this, "Don't find ticket.");
            return;
        }

        String boardingDateTime = t.getBoardingTime();
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
        LocalDateTime depatDateTime = LocalDateTime.parse(boardingDateTime, dtf);
        String deparDate = depatDateTime.toLocalDate().toString();
        String deparTime = depatDateTime.toLocalTime().toString();
        String boardingGate = t.getPort();
        
        //System.err.println(boardingGate+"=========");
        if (boardingGate.equals("0")) {
        
        }else{
         
            char terminal = boardingGate.charAt(0);
            char runway = boardingGate.charAt(1);
            String terString = "Not Availabel.";
            if (terminal == '1') {
                terString = "Ternimal A";
            } else if (terminal == '2') {
                terString = "Ternimal B";
            } else if (terminal == '3') {
                terString = "Ternimal C";
            } else
            ;

            String runwayString = "";
            if (runway == '1') {
                runwayString = "14";
            } else if (runway == '2') {
                runwayString = "16";
            } else if (runway == '3') {
                runwayString = "22";
            } else if (runway == '4') {
                runwayString = "27";
            } else ;

            txtGate.setText(terString + runwayString);
        }

        txtBording.setText(deparTime);
        txtLaggage.setText(t.getLaggageList());
        txtSeat.setText(t.getIdSeat());
        txtName.setText(p.getLegalName());
        txtFlightNo.setText(flightNo);
        txtDepaTime.setText(f.getDepartTime());
        txtArvTime.setText(f.getArrTime());
        txtDepatureAirport.setText(t.getFrom());
        txtArrivalAirport.setText(t.getTo());

    }
    public void setBlank(){
        txtBording.setText(" ");
        txtLaggage.setText(" ");
        txtSeat.setText(" ");
        txtName.setText(" ");
        txtFlightNo.setText(" ");
        txtDepaTime.setText(" ");
        txtArvTime.setText(" ");
        txtDepatureAirport.setText(" ");
        txtArrivalAirport.setText(" ");
        txtGate.setText(" ");
    }
}
