/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Passenger;

import dao.PassenagerDao;
import dao.PassportDao;
import java.util.Objects;
import javax.swing.JOptionPane;
import model.Passport;
import model.Person;
import org.apache.commons.lang3.ObjectUtils;
import org.apache.commons.lang3.StringUtils;
import utils.Constant;
import static utils.Constant.DATABASE_ERROR;

/**
 *
 * @author limingxia
 */
public class PassportInfoPanel extends javax.swing.JPanel {

    private Person curPerson;
    private Passport curPassport;

    /**
     * Creates new form PassportInfoPanel
     */
    public PassportInfoPanel() {
        curPerson = new Person();
        initComponents();
        initPassportInfo();

    }

    public PassportInfoPanel(Person curPerson) {
        this.curPerson = curPerson;
        initComponents();
        initPassportInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundPanel2 = new ui.component.RoundPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        expireDateTxt = new javax.swing.JTextField();
        nameTxt = new javax.swing.JTextField();
        passportNoTxt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        birthTxt = new javax.swing.JTextField();
        genderBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        countryBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        submitBtn = new javax.swing.JButton();

        roundPanel2.setBackground(new java.awt.Color(203, 238, 248));

        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("NAME");

        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("BIRTH DATE");

        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("VISA");

        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("PASSPORT NO.");

        expireDateTxt.setBackground(new java.awt.Color(203, 238, 248));
        expireDateTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        expireDateTxt.setToolTipText("MM/dd/yyyy");
        expireDateTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(106, 133, 182)));
        expireDateTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expireDateTxtActionPerformed(evt);
            }
        });

        nameTxt.setBackground(new java.awt.Color(203, 238, 248));
        nameTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(106, 133, 182)));
        nameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxtActionPerformed(evt);
            }
        });

        passportNoTxt.setBackground(new java.awt.Color(203, 238, 248));
        passportNoTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passportNoTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(106, 133, 182)));
        passportNoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passportNoTxtActionPerformed(evt);
            }
        });

        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("EXPIRED DATE");

        birthTxt.setBackground(new java.awt.Color(203, 238, 248));
        birthTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        birthTxt.setToolTipText("MM/dd/yyyy");
        birthTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(106, 133, 182)));
        birthTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthTxtActionPerformed(evt);
            }
        });

        genderBox.setBackground(new java.awt.Color(203, 238, 248));
        genderBox.setEditable(true);
        genderBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        genderBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Prefer not to say" }));
        genderBox.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(106, 133, 182)));
        genderBox.setOpaque(true);
        genderBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderBoxActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("SEX");

        countryBox.setBackground(new java.awt.Color(203, 238, 248));
        countryBox.setEditable(true);
        countryBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        countryBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "China", "India", "Tailand", "United Stats", "United Kindom" }));
        countryBox.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(106, 133, 182)));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/passport_64.png"))); // NOI18N

        javax.swing.GroupLayout roundPanel2Layout = new javax.swing.GroupLayout(roundPanel2);
        roundPanel2.setLayout(roundPanel2Layout);
        roundPanel2Layout.setHorizontalGroup(
            roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8)
                    .addComponent(nameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(genderBox, 0, 150, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(countryBox, 0, 150, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(roundPanel2Layout.createSequentialGroup()
                        .addGroup(roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(expireDateTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passportNoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(birthTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        roundPanel2Layout.setVerticalGroup(
            roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel2Layout.createSequentialGroup()
                        .addGroup(roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(roundPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(0, 0, 0)
                                .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(roundPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(0, 0, 0)
                                .addComponent(passportNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(birthTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(genderBox, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(expireDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(countryBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(222, 222, 222))))
        );

        submitBtn.setBackground(new java.awt.Color(48, 207, 208));
        submitBtn.setForeground(new java.awt.Color(255, 255, 255));
        submitBtn.setText("Submit");
        submitBtn.setBorder(null);
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roundPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(162, 162, 162)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(roundPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void expireDateTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expireDateTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expireDateTxtActionPerformed

    private void nameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxtActionPerformed

    private void passportNoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passportNoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passportNoTxtActionPerformed

    private void birthTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birthTxtActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        String legalName = nameTxt.getText();
        String visa = countryBox.getSelectedItem().toString();
        String passportID = passportNoTxt.getText();
        String birthday = birthTxt.getText();
        String expireDay = expireDateTxt.getText();

        Passport passport = new Passport(passportID, legalName, expireDay, visa, birthday);
        String warning = passport.checkField();
        if (StringUtils.isNotBlank(warning)) {
            JOptionPane.showMessageDialog(this, warning);
            return;
        }

        if (ObjectUtils.isEmpty(curPassport)) {
            if (!PassportDao.insertNewOne(passport)) {
                JOptionPane.showMessageDialog(this, DATABASE_ERROR);
                return;
            }

            if (!PassenagerDao.updatePassportID(curPerson.getPersonID(), passportID)) {
                JOptionPane.showMessageDialog(this, DATABASE_ERROR);
                return;
            }
        } else {
            if (!PassportDao.updatePassportnfo(passport)) {
                JOptionPane.showMessageDialog(this, DATABASE_ERROR);
                return;
            }
        }

        JOptionPane.showMessageDialog(this, "Successfully");
    }//GEN-LAST:event_submitBtnActionPerformed

    private void genderBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField birthTxt;
    private javax.swing.JComboBox<String> countryBox;
    private javax.swing.JTextField expireDateTxt;
    private javax.swing.JComboBox<String> genderBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JTextField passportNoTxt;
    private ui.component.RoundPanel roundPanel2;
    private javax.swing.JButton submitBtn;
    // End of variables declaration//GEN-END:variables

    private void initPassportInfo() {
        curPassport = PassportDao.queryPassportNoByPid(curPerson.getPersonID());
        if (Objects.isNull(curPassport)) {
            return;
        }

        nameTxt.setText(curPassport.getLegalName());
        // TODO only for test
        genderBox.setSelectedItem(curPerson.getGender());
        countryBox.setSelectedIndex(Constant.VISA_COUNTRY_LIST.indexOf(curPassport.getVisa()));
        passportNoTxt.setText(curPassport.getPassportNumber());
        birthTxt.setText(curPassport.getBirthday());
        expireDateTxt.setText(curPassport.getExpiryDate());

        // disable some buttons
        passportNoTxt.setEditable(false);
        birthTxt.setEditable(false);
        genderBox.setEnabled(false);
    }
}
