/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.systemadmin;

import dao.FlightDao;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Flight;
import model.PieChartItem;
import org.apache.commons.lang3.ObjectUtils;
import org.apache.commons.lang3.StringUtils;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;
import static ui.component.ComponetCommonMethod.setTableCenter;
import utils.Constant;
import static utils.Constant.SELECT_ERROR;

/**
 *
 * @author limingxia
 */
public class FlightManagement extends javax.swing.JPanel {

    private List<Flight> flights = new ArrayList<>();
    private Flight selectedFlight;
    private Boolean onlyView = false;

    /**
     * Creates new form AirlineManagement
     */
    public FlightManagement() {
        initComponents();
        setTableCenter(flightTable);
        refreshPanel();
    }

    public FlightManagement(boolean onlyView) {
        this.onlyView = onlyView;

        initComponents();

        setTableCenter(flightTable);
        refreshPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        searchAreaBg = new ui.component.RoundPanel();
        searchBtn = new javax.swing.JButton();
        keywordTxt = new javax.swing.JTextField();
        roundPanel1 = new ui.component.RoundPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        flightTable = new javax.swing.JTable();
        refreshBtn = new ui.component.RoundPanel();
        refreshLbl = new javax.swing.JLabel();
        alterPanel = new javax.swing.JPanel();
        submitBtn = new ui.component.RoundPanel();
        editBtn = new javax.swing.JLabel();
        submitBtn1 = new ui.component.RoundPanel();
        delBtn = new javax.swing.JLabel();
        submitBtn2 = new ui.component.RoundPanel();
        viewPieChart = new javax.swing.JLabel();
        submitBtn3 = new ui.component.RoundPanel();
        addFlightLbl = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setOpaque(false);

        searchAreaBg.setBackground(new java.awt.Color(255, 255, 255));

        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/search.png"))); // NOI18N
        searchBtn.setBorder(null);
        searchBtn.setBorderPainted(false);
        searchBtn.setOpaque(true);
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        keywordTxt.setToolTipText("");

        javax.swing.GroupLayout searchAreaBgLayout = new javax.swing.GroupLayout(searchAreaBg);
        searchAreaBg.setLayout(searchAreaBgLayout);
        searchAreaBgLayout.setHorizontalGroup(
            searchAreaBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchAreaBgLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(keywordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(searchBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        searchAreaBgLayout.setVerticalGroup(
            searchAreaBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchAreaBgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchAreaBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(keywordTxt))
                .addContainerGap())
        );

        roundPanel1.setBackground(new java.awt.Color(255, 255, 255));

        flightTable.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        flightTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Flight No", "Airline", "Departure", "Arrival"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        flightTable.setShowGrid(false);
        flightTable.getTableHeader().setReorderingAllowed(false);
        flightTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                flightTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(flightTable);
        if (flightTable.getColumnModel().getColumnCount() > 0) {
            flightTable.getColumnModel().getColumn(0).setPreferredWidth(5);
        }

        javax.swing.GroupLayout roundPanel1Layout = new javax.swing.GroupLayout(roundPanel1);
        roundPanel1.setLayout(roundPanel1Layout);
        roundPanel1Layout.setHorizontalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        roundPanel1Layout.setVerticalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        refreshBtn.setBackground(new java.awt.Color(255, 255, 255));

        refreshLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        refreshLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/refresh.png"))); // NOI18N
        refreshLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshLblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout refreshBtnLayout = new javax.swing.GroupLayout(refreshBtn);
        refreshBtn.setLayout(refreshBtnLayout);
        refreshBtnLayout.setHorizontalGroup(
            refreshBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(refreshLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );
        refreshBtnLayout.setVerticalGroup(
            refreshBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, refreshBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(refreshLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        alterPanel.setOpaque(false);

        submitBtn.setBackground(new java.awt.Color(255, 255, 255));
        submitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitBtnMouseClicked(evt);
            }
        });

        editBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/edit.png"))); // NOI18N
        editBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout submitBtnLayout = new javax.swing.GroupLayout(submitBtn);
        submitBtn.setLayout(submitBtnLayout);
        submitBtnLayout.setHorizontalGroup(
            submitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(submitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, submitBtnLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editBtn)
                    .addContainerGap()))
        );
        submitBtnLayout.setVerticalGroup(
            submitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(submitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(submitBtnLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(editBtn)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        submitBtn1.setBackground(new java.awt.Color(255, 255, 255));
        submitBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitBtn1MouseClicked(evt);
            }
        });

        delBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        delBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8-remove-24.png"))); // NOI18N
        delBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout submitBtn1Layout = new javax.swing.GroupLayout(submitBtn1);
        submitBtn1.setLayout(submitBtn1Layout);
        submitBtn1Layout.setHorizontalGroup(
            submitBtn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(submitBtn1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(delBtn)
                .addGap(8, 8, 8))
        );
        submitBtn1Layout.setVerticalGroup(
            submitBtn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(submitBtn1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(delBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        submitBtn2.setBackground(new java.awt.Color(255, 255, 255));
        submitBtn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitBtn2MouseClicked(evt);
            }
        });

        viewPieChart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewPieChart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/pieChart.png"))); // NOI18N
        viewPieChart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewPieChartMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout submitBtn2Layout = new javax.swing.GroupLayout(submitBtn2);
        submitBtn2.setLayout(submitBtn2Layout);
        submitBtn2Layout.setHorizontalGroup(
            submitBtn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(submitBtn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, submitBtn2Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewPieChart)
                    .addContainerGap()))
        );
        submitBtn2Layout.setVerticalGroup(
            submitBtn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(submitBtn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(submitBtn2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(viewPieChart)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        submitBtn3.setBackground(new java.awt.Color(255, 255, 255));
        submitBtn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitBtn3MouseClicked(evt);
            }
        });

        addFlightLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addFlightLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8-create-document-28.png"))); // NOI18N
        addFlightLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addFlightLblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout submitBtn3Layout = new javax.swing.GroupLayout(submitBtn3);
        submitBtn3.setLayout(submitBtn3Layout);
        submitBtn3Layout.setHorizontalGroup(
            submitBtn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(submitBtn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, submitBtn3Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addFlightLbl)
                    .addContainerGap()))
        );
        submitBtn3Layout.setVerticalGroup(
            submitBtn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(submitBtn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(submitBtn3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(addFlightLbl)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout alterPanelLayout = new javax.swing.GroupLayout(alterPanel);
        alterPanel.setLayout(alterPanelLayout);
        alterPanelLayout.setHorizontalGroup(
            alterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alterPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(submitBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(submitBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submitBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        alterPanelLayout.setVerticalGroup(
            alterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alterPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(alterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(submitBtn2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(submitBtn1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(submitBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(submitBtn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(roundPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(56, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(searchAreaBg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(alterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(refreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchAreaBg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(roundPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 717, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 565, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 12, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        String keyword = keywordTxt.getText();
        if (StringUtils.isBlank(keyword)) {
            JOptionPane.showMessageDialog(this, "Please input keyword!");
            refreshPanel();
            return;
        }

        List<Flight> searchResult = flights.stream().filter(a
                -> a.getFlightNo().equalsIgnoreCase(keyword)
                || a.getFlightCompany().getFcName().equalsIgnoreCase(keyword)
        ).collect(Collectors.toList());

        populateTable(searchResult);
    }//GEN-LAST:event_searchBtnActionPerformed

    private void flightTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flightTableMouseClicked

    }//GEN-LAST:event_flightTableMouseClicked

    private void refreshLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshLblMouseClicked
        refreshPanel();
    }//GEN-LAST:event_refreshLblMouseClicked

    private void editBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editBtnMouseClicked
        int selectedRowIndex = flightTable.getSelectedRow();
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, SELECT_ERROR);
            return;
        }

        DefaultTableModel model = (DefaultTableModel) flightTable.getModel();
        Flight flight = (Flight) model.getValueAt(selectedRowIndex, 0);

        SAEditFlightFrame aoeff = new SAEditFlightFrame(flight);
        aoeff.setVisible(true);
    }//GEN-LAST:event_editBtnMouseClicked

    private void submitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitBtnMouseClicked

    }//GEN-LAST:event_submitBtnMouseClicked

    private void delBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delBtnMouseClicked
        int selectedRowIndex = flightTable.getSelectedRow();
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, Constant.SELECT_ERROR);
            return;
        }

        DefaultTableModel model = (DefaultTableModel) flightTable.getModel();
        Flight flight = (Flight) model.getValueAt(selectedRowIndex, 0);

        if (!FlightDao.realDeleteFlightByID(flight.getFlightNo())) {
            JOptionPane.showMessageDialog(this, Constant.DATABASE_ERROR);
            return;
        }

        JOptionPane.showMessageDialog(this, Constant.SUCC);

        refreshPanel();

    }//GEN-LAST:event_delBtnMouseClicked

    private void submitBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitBtn1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_submitBtn1MouseClicked

    private void viewPieChartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewPieChartMouseClicked
        List<PieChartItem> piecharList = FlightDao.flightStatusStat();

        DefaultPieDataset dpd = new DefaultPieDataset();
        for (PieChartItem pci : piecharList) {
            dpd.setValue(pci.getText(), pci.getValue());
        }

        JFreeChart chart = ChartFactory.createPieChart("All Flight Status ", dpd, true,
                true, false);

        ChartFrame chartFrame = new ChartFrame("", chart);
        chartFrame.pack();
        //chartFrame.setUndecorated(true);
        chartFrame.setLocationRelativeTo(null);
        chartFrame.setVisible(true);
    }//GEN-LAST:event_viewPieChartMouseClicked

    private void submitBtn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitBtn2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_submitBtn2MouseClicked

    private void addFlightLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addFlightLblMouseClicked

        CreateFlight createFlight = new CreateFlight();
        createFlight.setVisible(true);
    }//GEN-LAST:event_addFlightLblMouseClicked

    private void submitBtn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitBtn3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_submitBtn3MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addFlightLbl;
    private javax.swing.JPanel alterPanel;
    private javax.swing.JLabel delBtn;
    private javax.swing.JLabel editBtn;
    private javax.swing.JTable flightTable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField keywordTxt;
    private ui.component.RoundPanel refreshBtn;
    private javax.swing.JLabel refreshLbl;
    private ui.component.RoundPanel roundPanel1;
    private ui.component.RoundPanel searchAreaBg;
    private javax.swing.JButton searchBtn;
    private ui.component.RoundPanel submitBtn;
    private ui.component.RoundPanel submitBtn1;
    private ui.component.RoundPanel submitBtn2;
    private ui.component.RoundPanel submitBtn3;
    private javax.swing.JLabel viewPieChart;
    // End of variables declaration//GEN-END:variables

    private void initFlights() {
        flights = FlightDao.queryFlightList();
    }

    private void populateTable(List<Flight> flights) {
        DefaultTableModel model = (DefaultTableModel) flightTable.getModel();
        model.setRowCount(0);

        if (ObjectUtils.isEmpty(flights)) {
            return;
        }

        for (Flight f : flights) {

            Object[] row = new Object[5];
            row[0] = f;
            row[1] = f.getFlightCompany().getFcName();
            row[2] = f.getDepartTime();
            row[3] = f.getArrTime();
            row[4] = Constant.FLIGHT_STATUS[f.getStatus()];

            model.addRow(row);
        }
    }

    private void refreshPanel() {
        if (onlyView) {
            alterPanel.setVisible(false);
        }
        keywordTxt.setText("");
        initFlights();
        populateTable(flights);
    }
}
