/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.companyadmin;

import dao.PersonDao;
import enumvalue.RoleEnum;
import java.awt.Component;
import java.util.ArrayList;
import java.util.Arrays;
import model.FCAdmin;
import model.Person;
import ui.HomePage;
import ui.component.ClickLabelEvent;
import ui.component.FuncItem;
import ui.systemadmin.SystemAdminFrame;

/**
 *
 * @author Jiaf
 */
public class CompanyAdminFrame extends javax.swing.JFrame {

    private ArrayList<FuncItem> funcItemList;
    FCAdmin fcAdmin = new FCAdmin();
    Person curPerson = new Person();
    int flightComId;

    private class CompanyAdminEvent implements ui.component.CustomEvent {

        @Override
        public void funcItemSelected(int index) {
            // TODO add new panel here
            switch (index) {
                case 0:
                    showContent(new ComFlightManagement(fcAdmin));
                    break;
                case 1:
                    showContent(new AddNewCompanyFlight(fcAdmin.getFcid()));
                    break;
                default:
                // throw new AssertionError();
            }
        }
    }
    
    /**
     * Creates new form CompanyAdminFrame
     */
    public CompanyAdminFrame(){
        fcAdmin.setAccount("ca@gamil.com");
        fcAdmin.setFcid(2);
        
        initFuncItemList();
        initComponents();
        
        sideBarPanel.initMenu(funcItemList, new CompanyAdminFrame.CompanyAdminEvent(), new ExitEvent());
    }
    
    public CompanyAdminFrame(Person p) {
        castPersonType(p);        
        //fcAdmin.setAccount(p.getAccount());

        initFuncItemList();
        initComponents();

        sideBarPanel.initMenu(funcItemList, new CompanyAdminFrame.CompanyAdminEvent(), new ExitEvent());
    }
    
    private void castPersonType(Person p){
        fcAdmin.setAccount(p.getAccount());
        fcAdmin.setAge(p.getAge());
        fcAdmin.setGender(p.getGender());
        fcAdmin.setPassword(p.getPassword());
        fcAdmin.setPersonID(p.getPersonID());
        fcAdmin.setPersonName(p.getPersonName());
        fcAdmin.setRoleType(p.getRoleType());
        
        this.flightComId = PersonDao.queryFcAdminCompanyId(fcAdmin.getAccount());
        fcAdmin.setFcid(flightComId);
    }

    private class ExitEvent implements ClickLabelEvent {

        @Override
        public void labelClick() {
            backToSignIn();
        }

    }

    private void backToSignIn() {
        HomePage homePage = new HomePage();
        homePage.setVisible(true);
        this.dispose();
    }

    private void showContent(Component component) {
        contentPanel.removeAll();
        contentPanel.add(component);
        this.validate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        sideBarPanel = new ui.SideBarPanel(fcAdmin);
        contentPanel = new javax.swing.JPanel();
        toolPanel1 = new ui.component.toolBarPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setkEndColor(new java.awt.Color(51, 8, 103));
        kGradientPanel1.setkStartColor(new java.awt.Color(48, 207, 208));

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sideBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(sideBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        contentPanel.setBackground(new java.awt.Color(204, 204, 204));
        contentPanel.setOpaque(false);
        contentPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(toolPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(toolPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompanyAdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompanyAdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompanyAdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompanyAdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompanyAdminFrame().setVisible(true);
            }
        });
    }
    
        private void initFuncItemList() {
        this.funcItemList = new ArrayList<>(
                Arrays.asList(
                        new FuncItem("list", "All Flights", 0),
                        new FuncItem("addflight", "New Flight", 1)
                )
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPanel;
    private keeptoo.KGradientPanel kGradientPanel1;
    private ui.SideBarPanel sideBarPanel;
    private ui.component.toolBarPanel toolPanel1;
    // End of variables declaration//GEN-END:variables
}
